<a href="https://colab.research.google.com/github/yousef333mohamed/app/blob/main/Copy_of_Python_Numpy_Exercises_with_hints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python NumPy Exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` and print the numpy version and the configuration (★☆☆)

`Hint: import … as` and `np.__version__, np.show_config)`

In [1]:
import numpy as np
np.show_config()


Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name: gcc


*italicized text*#### 2. Convert a list of numeric value into a one-dimensional NumPy array (★☆☆)
`💡 hint: numpy.array`

In [2]:
import numpy as np
my_list = [1, 2, 3, 4, 5]

arr = np.array(my_list)

print(arr)
print("Type:", type(arr))


[1 2 3 4 5]
Type: <class 'numpy.ndarray'>


#### 3. Create a null vector of size 9 (★☆☆)
`💡 hint: np.zeros`

In [3]:
import numpy as np

# Create a null vector (all zeros) of size 9
null_vector = np.zeros(9)

print(null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0.]


bold text#### 4. How to find the memory size of any array (★☆☆)
`💡 hint: size, itemsize`

In [4]:
import numpy as np

# Example array
arr = np.array([1, 2, 3, 4, 5])

# Memory size in bytes
memory_size = arr.size * arr.itemsize

print("Memory size of array:", memory_size, "bytes")


Memory size of array: 40 bytes


# **bold text**#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
`💡hint: np.info`

In [5]:
import numpy as np

# Get documentation for numpy.add
np.info(np.add)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

# #### 6. Create a null vector of size 12 but the sixth value which is 1 (★☆☆)
`💡hint: array[12]`

In [6]:
import numpy as np

# Create a null vector of size 12
arr = np.zeros(12)

# Set the sixth value to 1
arr[5] = 1   # Index 5 because indexing starts at 0

print(arr)



[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


# #### 7. Create a vector with values ranging from 20 to 59 (★☆☆)
`💡hint: arange`

In [7]:
import numpy as np

# Create vector from 20 to 59
arr = np.arange(20, 60)

print(arr)



[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


#
# `💡hint: array[::-**italicized text**#### 8. Reverse a vector (first element becomes last) (★☆☆)1]`

In [8]:
import numpy as np

# Example vector
arr = np.arange(1, 6)  # [1 2 3 4 5]

# Reverse it
reversed_arr = arr[::-1]

print(reversed_arr)


[5 4 3 2 1]


# bold text#### 9. Create a 3x3 matrix with values ranging from 12 to 20 (★☆☆)
`💡hint: reshape`

In [9]:
import numpy as np

# Create values from 12 to 20 (inclusive)
arr = np.arange(12, 21).reshape(3, 3)

print(arr)


[[12 13 14]
 [15 16 17]
 [18 19 20]]


# **bold text**#### 10. Find indices of non-zero elements from [3,7,0,0,9,0] (★☆☆)
`💡hint: np.nonzero`

> Add blockquote

# > Add blockquote





In [10]:
import numpy as np

# المصفوفة المعطاة
arr = np.array([3, 7, 0, 0, 9, 0])

# إيجاد أماكن (إندكسات) العناصر الغير صفرية
indices = np.nonzero(arr)

print(indices)


(array([0, 1, 4]),)


#### 11. Create a 4x4 identity matrix (★☆☆)
`💡hint: np.eye`

In [11]:
import numpy as np

# إنشاء مصفوفة هوية 4x4
identity_matrix = np.eye(4)

print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# #### 12. Create a 2x2x2 array with random values (★☆☆)
`💡hint: np.random.random`

In [12]:
import numpy as np

# إنشاء مصفوفة أبعادها 2x2x2 بقيم عشوائية بين 0 و 1
arr = np.random.random((2, 2, 2))

print(arr)


[[[0.86088946 0.90171523]
  [0.08131207 0.35000972]]

 [[0.80706064 0.44470133]
  [0.37983069 0.49628196]]]


# italicized text#### 13. Create a 9x9 array with random values and find the minimum and maximum values (★☆☆)
`💡hint: min, max`

In [13]:
import numpy as np

# إنشاء مصفوفة 9x9 بقيم عشوائية بين 0 و 1
arr = np.random.random((9, 9))

# إيجاد أقل قيمة
min_value = arr.min()

# إيجاد أكبر قيمة
max_value = arr.max()

print("المصفوفة:\n", arr)
print("أقل قيمة:", min_value)
print("أكبر قيمة:", max_value)


المصفوفة:
 [[0.01234567 0.93069384 0.98716091 0.91736785 0.58978809 0.58594979
  0.65730702 0.1783127  0.15968458]
 [0.94160899 0.14457541 0.21219554 0.17077741 0.778493   0.42981306
  0.401931   0.86701587 0.28056718]
 [0.52312284 0.437106   0.86925775 0.84114012 0.83285809 0.47449752
  0.37167914 0.42920275 0.42040377]
 [0.18890307 0.38031003 0.14212033 0.51319066 0.78943389 0.24263425
  0.45535154 0.68724219 0.55029507]
 [0.49410085 0.77790163 0.57203898 0.56107121 0.52487644 0.04660282
  0.80529129 0.90082547 0.5454336 ]
 [0.40922894 0.5707475  0.20779432 0.98556758 0.44424864 0.05788441
  0.14143152 0.61150529 0.58516553]
 [0.63567113 0.84168759 0.68210808 0.68652829 0.1041372  0.18384995
  0.18422306 0.62721702 0.46666086]
 [0.42785383 0.04546988 0.80964314 0.4138555  0.03231653 0.43783832
  0.37280092 0.77170043 0.46707038]
 [0.50313867 0.44016545 0.75152214 0.40117675 0.76203756 0.93671488
  0.83340612 0.845619   0.76343348]]
أقل قيمة: 0.01234567330473657
أكبر قيمة: 0.987160911



```
## This is formatted as code
```

#### 14. Create a random vector of size 20 and find the mean value (★☆☆)
`💡hint: mean`

In [14]:
import numpy as np

# إنشاء متجه عشوائي حجمه 20
arr = np.random.random(20)

# حساب المتوسط
mean_value = arr.mean()

print("المتجه:", arr)
print("المتوسط:", mean_value)


المتجه: [0.38834556 0.87692689 0.98090066 0.05452664 0.26436129 0.85355463
 0.42587876 0.57980073 0.71374615 0.2935262  0.93938507 0.30493194
 0.17756333 0.4456267  0.24131065 0.23209995 0.54451575 0.51881212
 0.76777407 0.80359808]
المتوسط: 0.520359258015675


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
`💡hint: array[1:-1, 1:-1]`

In [15]:
import numpy as np

# إنشاء مصفوفة 2D أبعادها 5x5 كلها أصفار
arr = np.zeros((5, 5))

# جعل الحدود قيمها 1
arr[0, :] = 1        # الصف الأول
arr[-1, :] = 1       # الصف الأخير
arr[:, 0] = 1        # العمود الأول
arr[:, -1] = 1       # العمود الأخير

print(arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
`💡hint: np.pad`

In [16]:

import numpy as np

# مصفوفة أصلية
arr = np.ones((3, 3))

# إضافة حدود أصفار حول المصفوفة
arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(arr_with_border)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# **bold text**#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```
`💡hint: NaN = not a number, inf = infinity`

#### 18. Create a 6x6 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`💡hint: np.diag`

In [17]:
import numpy as np

arr = np.diag(1 + np.arange(4), k=-1)

print(arr)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]




```
# This is formatted as code
```

#### 19. Create a 6x6 matrix and fill it with a checkerboard pattern (★☆☆)
`💡hint: array[::2]`

In [18]:
import numpy as np

# إنشاء مصفوفة 6x6 كلها أصفار
arr = np.zeros((6, 6), dtype=int)

# جعل نمط الشطرنج
arr[::2, 1::2] = 1  # الصفوف الزوجية - الأعمدة الفردية
arr[1::2, ::2] = 1  # الصفوف الفردية - الأعمدة الزوجية

print(arr)


[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


#### 20. Consider a (8,9,10) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
`💡hint: np.unravel_index`

In [19]:
import numpy as np

# إيجاد إحداثيات العنصر رقم 100 في مصفوفة أبعادها (8, 9, 10)
index = np.unravel_index(100, (8, 9, 10))

print(index)


(np.int64(1), np.int64(1), np.int64(0))


*italicized text*#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
`💡hint: np.tile`

In [20]:
import numpy as np

# إنشاء مصفوفة شطرنج 8x8 باستخدام np.tile
checkerboard = np.tile([[0, 1], [1, 0]], (4, 4))

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 6x6 random matrix (★☆☆)
`💡hint: (x -mean)/std`

In [21]:
import numpy as np

# إنشاء مصفوفة 6x6 بقيم عشوائية
arr = np.random.random((6, 6))

# حساب المتوسط والانحراف المعياري
mean = arr.mean()
std = arr.std()

# عمل Normalization
normalized_arr = (arr - mean) / std

print("المصفوفة الأصلية:\n", arr)
print("\nالمصفوفة بعد التطبيع (Normalization):\n", normalized_arr)


المصفوفة الأصلية:
 [[0.54142851 0.52535343 0.29004599 0.7157561  0.22702335 0.35353192]
 [0.72508604 0.6369716  0.18469822 0.97197112 0.62248147 0.42485173]
 [0.03603484 0.806824   0.91403682 0.72818238 0.18647263 0.08156814]
 [0.64693856 0.41102196 0.05952925 0.91524022 0.75605403 0.68191137]
 [0.77067963 0.60290312 0.01684333 0.91098552 0.82472474 0.24205508]
 [0.30716223 0.175135   0.52595422 0.2591773  0.62457443 0.43688567]]

المصفوفة بعد التطبيع (Normalization):
 [[ 0.13506395  0.07722335 -0.76944912  0.7623215  -0.99621428 -0.54101695]
 [ 0.79589207  0.47884274 -1.14850664  1.68422263  0.426705   -0.28439729]
 [-1.6834204   1.08999784  1.4757661   0.80703318 -1.14212202 -1.51958457]
 [ 0.51470537 -0.3341589  -1.59888389  1.48009612  0.90731967  0.64054294]
 [ 0.95994481  0.35625909 -1.75247439  1.46478707  1.15440748 -0.94212779]
 [-0.70786225 -1.18291657  0.07938508 -0.88051941  0.43423581 -0.24109732]]


#### 23. find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. (★☆☆)

In [22]:
import numpy as np

# إنشاء مصفوفة كمثال
arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)

# عدد العناصر
num_elements = arr.size

# حجم كل عنصر بالبايت
element_size = arr.itemsize

# إجمالي حجم المصفوفة بالبايت
total_bytes = arr.nbytes

print("عدد العناصر:", num_elements)
print("حجم كل عنصر (بايت):", element_size)
print("إجمالي الحجم (بايت):", total_bytes)


عدد العناصر: 5
حجم كل عنصر (بايت): 4
إجمالي الحجم (بايت): 20


**bold text**#### 24. Multiply a 6x3 matrix by a 3x4 matrix (real matrix product) (★☆☆)
`💡hint: np.dot` or `np.ones`

In [23]:
import numpy as np

# إنشاء مصفوفة 6x3 كلها واحدات
A = np.ones((6, 3))

# إنشاء مصفوفة 3x4 كلها واحدات
B = np.ones((3, 4))

# الضرب الحقيقي للمصفوفات
C = np.dot(A, B)

print(C)


[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
`💡hint: >, <`

In [24]:
import numpy as np

# إنشاء مصفوفة 1D كمثال
arr = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]

# عكس إشارة القيم بين 3 و 8 (حصري)
arr[(arr > 3) & (arr < 8)] *= -1

print(arr)


[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [25]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))


9
10


#### 27. Write a Python program compare two arrays using numpy (★☆☆)
```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [26]:
import numpy as np

# تعريف المصفوفتين
a = np.array([1, 2])
b = np.array([4, 5])

print("Array a:", a)
print("Array b:", b)

print("a > b :", a > b)
print("a >= b:", a >= b)
print("a < b :", a < b)
print("a <= b:", a <= b)


Array a: [1 2]
Array b: [4 5]
a > b : [False False]
a >= b: [False False]
a < b : [ True  True]
a <= b: [ True  True]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```
Consider an integer vector a
```python
a**a
a << a >> 2
a <- a
1j*a
a/1/1
a<a>a
```

In [27]:
import numpy as np

# الجزء الأول
print("np.array(0) / np.array(0) =>", np.array(0) / np.array(0))  # قسمة صفر على صفر
print("np.array(0) // np.array(0) =>", np.array(0) // np.array(0))  # قسمة صحيحة صفر على صفر
print("np.array([np.nan]).astype(int).astype(float) =>", np.array([np.nan]).astype(int).astype(float))  # تحويل NaN

# إنشاء متجه a
a = np.array([1, 2, 3], dtype=int)

# عمليات مختلفة على المتجه
print("a ** a =>", a ** a)  # أس كل عنصر بنفسه
print("a << a >> 2 =>", a << a >> 2)  # إزاحة بتات لليسار ثم لليمين
print("a < -a =>", a < -a)  # مقارنة القيم مع سالبها
print("1j * a =>", 1j * a)  # ضرب بالأعداد المركبة
print("a / 1 / 1 =>", a / 1 / 1)  # قسمة على 1 مرتين
print("a < a > a =>", a < a > a)  # مقارنة منطقية متسلسلة


np.array(0) / np.array(0) => nan
np.array(0) // np.array(0) => 0
np.array([np.nan]).astype(int).astype(float) => [-9.22337204e+18]
a ** a => [ 1  4 27]
a << a >> 2 => [0 2 6]
a < -a => [False False False]
1j * a => [0.+1.j 0.+2.j 0.+3.j]
a / 1 / 1 => [1. 2. 3.]


/tmp/ipython-input-1066748133.py:4: RuntimeWarning: invalid value encountered in divide
  print("np.array(0) / np.array(0) =>", np.array(0) / np.array(0))  # قسمة صفر على صفر
/tmp/ipython-input-1066748133.py:5: RuntimeWarning: divide by zero encountered in floor_divide
  print("np.array(0) // np.array(0) =>", np.array(0) // np.array(0))  # قسمة صحيحة صفر على صفر
/tmp/ipython-input-1066748133.py:6: RuntimeWarning: invalid value encountered in cast
  print("np.array([np.nan]).astype(int).astype(float) =>", np.array([np.nan]).astype(int).astype(float))  # تحويل NaN


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 29. How to round away from zero a float array ? (★☆☆)
`💡hint: np.uniform, np.copysign, np.ceil, np.abs, np.where`

In [28]:
import numpy as np

# إنشاء مصفوفة أعداد عشرية عشوائية بين -10 و 10
arr = np.random.uniform(-10, 10, 10)
print("الأرقام الأصلية:")
print(arr)

# تقريب بعيد عن الصفر
rounded = np.copysign(np.ceil(np.abs(arr)), arr)
print("\nبعد التقريب بعيد عن الصفر:")
print(rounded)


الأرقام الأصلية:
[-5.63213068 -9.65128703  8.62769551  7.02286328 -7.74460466 -2.14443174
  6.73133989  6.92429545  7.72336765 -3.31592078]

بعد التقريب بعيد عن الصفر:
[ -6. -10.   9.   8.  -8.  -3.   7.   7.   8.  -4.]


#### 30. How to find common values between two arrays? (★☆☆)
`💡hint: np.intersect1d`

In [29]:
import numpy as np

# إنشاء مصفوفتين (Arrays) بشكل عشوائي
arr1 = np.array([1, 3, 4, 6, 8])
arr2 = np.array([2, 4, 6, 8, 10])

# إيجاد القيم المشتركة بين المصفوفتين
common_values = np.intersect1d(arr1, arr2)

print("المصفوفة الأولى:", arr1)
print("المصفوفة الثانية:", arr2)
print("القيم المشتركة:", common_values)


المصفوفة الأولى: [1 3 4 6 8]
المصفوفة الثانية: [ 2  4  6  8 10]
القيم المشتركة: [4 6 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
`💡hint: np.seterr, np.errstate`

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```
`💡hint: imaginary number`

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
`💡hint: np.datetime64, np.timedelta64`

#### 34. How to get all the dates corresponding to the month of January 2016? (★★☆)
`💡hint: np.arange(dtype=datetime64['D'])`

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
`💡hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)`

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
`💡hint: %, np.floor, astype, np.trunc`

#### 37. Create a 3x3 matrix with row values ranging from 0 to 2 (★★☆)
`💡hint: np.arange`

#### 38. Consider a generator function that generates 9 integers and use it to build an array (★☆☆)
`💡hint: np.fromiter`

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
`💡hint: np.linspace`

#### 40. Create a random vector of size 10 and sort it (★★☆)
`💡hint: sort`

#### 41. How to sum a small array faster than np.sum? (★★☆)
`💡hint: np.add.reduce`

#### 42. Consider two random array A and B, check if they are equal (★★☆)
`💡hint: np.allclose, np.array_equal`

#### 43. Make an array immutable (read-only) (★★☆)
`💡hint: flags.writeable`

#### 44. Consider a random 5x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
`💡hint: np.sqrt, np.arctan2`

#### 45. Create random vector of size 5 and replace the maximum value by 0 (★★☆)
`💡hint: argmax`

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
`💡hint: np.meshgrid`

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
`💡hint: np.subtract.outer`

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
`💡hint: np.iinfo, np.finfo, eps`

#### 49. How to print all the values of an array? (★★☆)
`💡hint: np.set_printoptions`

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
`💡hint: argmin`

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
`💡hint: dtype`

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
`💡hint: np.atleast_2d, T, np.sqrt`

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
`💡hint: view and [:] =`

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```
`💡hint: np.genfromtxt`

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
`💡hint: np.ndenumerate, np.ndindex`

#### 56. Generate a generic 2D Gaussian-like array (★★☆)
`💡hint: np.meshgrid, np.exp`

#### 57. How to randomly place e elements in a 2D array? (★★☆)
`💡hint: np.put, np.random.choice`

#### 58. Subtract the mean of each row of a matrix (★★☆)
`💡hint: mean(axis=,keepdims=)`

#### 59. How to sort an array by the nth column? (★★☆)
`💡hint: argsort`

#### 60. How to tell if a given 2D array has null columns? (★★☆)
`💡hint: any, ~`

#### 61. Find the nearest value from a given value in an array (★★☆)
`💡hint: np.abs, argmin, flat`

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
`💡

#### 63. Create an array class that has a name attribute (★★☆)
`💡hint: class method`

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
`💡hint: np.bincount | np.add.at`

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
`💡hint: np.bincount`

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
`💡hint: np.unique`

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
`💡hint: sum(axis=(-2,-1))`

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
`💡hint: np.bincount`

#### 69. How to get the diagonal of a dot product? (★★★)
`💡hint: np.diag`

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
`💡hint: array[::4]`

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
`💡hint: array[:, :, None]`

#### 72. How to swap two rows of an array? (★★★)
`💡hint: array[[]] = array[[]]`

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
`💡hint: repeat, np.roll, np.sort, view, np.unique`

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
`💡hint: np.repeat`

#### 75. How to compute averages using a sliding window over an array? (★★★)
`💡hint: np.cumsum`

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
`💡hint: from numpy.lib import stride_tricks`

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
`💡hint: np.logical_not, np.negative`

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
`💡hint: minimum maximum`

#### 81. Consider an array a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
`💡hint: stride_tricks.as_strided`

#### 82. Compute a matrix rank (★★★)
`💡hint: np.linalg.svd`

#### 83. How to find the most frequent value in an array?
`💡hint: np.bincount, argmax`

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
`💡hint: stride_tricks.as_strided`

#### 85. Create a 2D array subclass such that a[i,j] == a[j,i] (★★★)
`💡hint: class method`

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
`💡hint: np.tensordot`

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
`💡hint: np.add.reduceat`

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)
`💡hint: np.argsort | np.argpartition`

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
`💡hint: np.indices`

#### 91. How to create a record array from a regular array? (★★★)
`💡hint: np.core.records.fromarrays`

#### 92. Consider a large vector A, compute A to the power of 3 using 3 different methods (★★★)
`💡hint: np.power, *, np.einsum`

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
`💡hint: np.where`

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)
`💡hint: np.unpackbits`

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
`💡hint: np.ascontiguousarray | np.unique`

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
`💡hint: np.einsum`

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
`💡hint: np.cumsum, np.interp`

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
`💡hint: np.logical_and.reduce, np.mod`

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
`💡hint: np.percentile`